import { useMemo, useState } from "react";
import { BalanceContext } from "../../CustomHooks/BalanceContext";

const initialBalance = {
  totalBalance: 1000,
  targetIncome: 1000,
  utilitiesBillLimit: 1000,
  transportationLimit: 1000,
  foodDiningLimit: 1000,
  otherExpenseLimit: 1000,
  entertainment: 1000,
  transaction: [
    {
      title: "Monthly Salary",
      date: "2026-03-20",
      amount: 4500.0,
      category: "Salary & Payroll",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Grocery Shopping",
      date: "2026-04-05",
      amount: 142.5,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "Freelance Project",
      date: "2026-04-18",
      amount: 850.0,
      category: "Salary & Payroll",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Dinner with Friends",
      date: "2026-09-12",
      amount: 88.2,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "Monthly Salary",
      date: "2026-06-01",
      amount: 4500.0,
      category: "Salary & Payroll",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Weekly Supermarket",
      date: "2026-06-22",
      amount: 210.35,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "Stock Dividend",
      date: "2026-07-14",
      amount: 120.0,
      category: "Salary & Payroll",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Coffee & Bakery",
      date: "2026-08-03",
      amount: 18.5,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "Consulting Payment",
      date: "2026-08-29",
      amount: 650.0,
      category: "Salary & Payroll",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Weekend Takeout",
      date: "2026-09-12",
      amount: 34.75,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "Apartment Rent",
      date: "2026-03-25",
      amount: 1200.0,
      category: "Rent & Housing",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#abace4]",
      bg: "bg-[#34333c]",
    },
    {
      title: "Monthly Salary",
      date: "2026-04-01",
      amount: 4500.0,
      category: "Salary & Payroll",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Grocery Shopping",
      date: "2026-04-12",
      amount: 145.2,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "UI Design Project",
      date: "2026-05-04",
      amount: 850.0,
      category: "Freelance",
      transactionType: "Credit",
      type: "income",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Electricity & Water Bill",
      date: "2026-05-18",
      amount: 165.5,
      category: "Utilities & Bills",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#abace4]",
      bg: "bg-[#34333c]",
    },
    {
      title: "Movie & Arcade Night",
      date: "2026-06-05",
      amount: 45.0,
      category: "Entertainment",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#44c08c]",
      bg: "bg-[#23372e]",
    },
    {
      title: "Stock Dividend Payout",
      date: "2026-06-28",
      amount: 210.0,
      category: "Investments",
      transactionType: "Credit",
      type: "income",
      text: "text-[#abace4]",
      bg: "bg-[#34333c]",
    },
    {
      title: "Monthly Bus Pass",
      date: "2026-07-15",
      amount: 75.0,
      category: "Transportation",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#abace4]",
      bg: "bg-[#34333c]",
    },
    {
      title: "Dental Checkup",
      date: "2026-08-10",
      amount: 120.0,
      category: "Healthcare",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
    {
      title: "Dinner with Friends",
      date: "2026-09-02",
      amount: 68.4,
      category: "Food & Dining",
      transactionType: "Credit",
      type: "expense",
      text: "text-[#ffb2b7]",
      bg: "bg-[#3d282a]",
    },
  ],
};

export const BalanceProvider = ({ children }) => {
  const [balance, setBalance] = useState(initialBalance);
  const value = useMemo(() => ({ balance, setBalance }), [balance]);
  return <BalanceContext value={value}>{children}</BalanceContext>;
};

export default BalanceContext;
